---
# Three node deployment:
# - PostgreSQL database
# - OMERO.server
# - OMERO.web

- hosts: all
  tasks:
    - name: Set OS distribution dependent variables
      include_vars: "{{ ansible_facts['os_family'] | lower }}.yml"
      when: ansible_facts['os_family'] == "Debian"

# gather cross-host vars
- hosts: all
  tasks:
    - name: Get omero IP addresses
      set_fact:
        omero_database_address: >-
          {{ hostvars[groups['omero_database'][0]].ansible_default_ipv4.address }}
        omero_server_address: >-
            {{ hostvars[groups['omero_server'][0]].ansible_default_ipv4.address }}

# turn off firewall for internal hosts (not for production!)
- hosts: all
  roles:
    - role: ome.iptables_raw

  tasks:
    - name: Iptables internal hosts allow all
      become: yes
      iptables_raw_25:
        name: default_accept
        keep_unmanaged: no
        rules: |
          -A INPUT -j ACCEPT
          -A FORWARD -j ACCEPT
          -A OUTPUT -j ACCEPT
        state: present
        # Highest priority
        weight: 0

- hosts: omero_database
  roles:
    - role: ome.postgresql

  vars:
    postgresql_server_listen: "'*'"
    postgresql_server_auth:
      - database: omero
        user: omero
        address: 0.0.0.0/0
    postgresql_databases:
      - name: omero
    postgresql_users:
      - user: omero
        password: omero
        databases: [omero]
    postgresql_version: "11"

- hosts: omero_server
  roles:
    - role: ome.omero_server

  vars:
    omero_server_dbhost: "{{ omero_database_address }}"
    postgresql_version: "11"
    omero_server_dbuser: omero
    omero_server_dbpassword: omero

- hosts: omero_web
  roles:
    - role: ome.basedeps
    - role: ome.omero_web

  vars:
    omero_web_config_set:
      omero.web.server_list:
        - ["{{ omero_server_address }}", 4064, omero]
