---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: omero-database
    image: jrei/systemd-ubuntu:18.04
    privileged: true
    command: /sbin/init
    tmpfs:
      - /sys/fs/cgroup
  - name: omero-server
    image: jrei/systemd-ubuntu:18.04
    privileged: true
    command: /sbin/init
    tmpfs:
      - /sys/fs/cgroup
  - name: omero-web
    image: jrei/systemd-ubuntu:18.04
    privileged: true
    command: /sbin/init
    tmpfs:
      - /sys/fs/cgroup
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../../playbook.yml
scenario:
  name: ubuntu1804
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
